<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.16" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmolPass.Application\SmolPass.Application.csproj" />
    <ProjectReference Include="..\SmolPass.Infrastructure\SmolPass.Infrastructure.csproj" />
    <ProjectReference Include="..\SmolPass.Contracts\SmolPass.Contracts.csproj" />
  </ItemGroup>

</Project>
